### ISSUE TITLE
Injecting AnnotationConfigApplicationContext into AxonAutoConfiguration does not work for web applications

### ISSUE THREAD

**Issue by premanandc** [binkley/spring-boot-starter-axon#17]
While this appears to work in tests, it doesn't work when you add the @WebIntegrationTest annotation test like below. Needless to say, this also doesn't work in real applications.

```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = RepositoriesTestConfiguration.class)
@WebIntegrationTest
public final class RepositoriesIT {
    @Autowired
    private AnnotationConfigApplicationContext context;
    @Autowired
    @Qualifier("repositoriesTestAggregateRootRepository")
    private EventSourcingRepository<RepositoriesTestAggregateRoot> repository;
    @Autowired
    @Qualifier("repositoriesTestAggregateRootRepository")
    private Repository<RepositoriesTestAggregateRoot> duplicate;

    @Test
    public void shouldWireRepository() {
        assertThat(repository).isNotNull();
    }

    @Test
    public void shouldCreateSingleton() {
        assertThat(duplicate).isSameAs(repository);
    }
}

```

The above causes

```

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.context.annotation.AnnotationConfigApplicationContext hm.binkley.spring.axon.AxonAutoConfiguration.context; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.context.annotation.AnnotationConfigApplicationContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
    ... 55 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.context.annotation.AnnotationConfigApplicationContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
    ... 57 more

```

**Comment by binkley** [comment]
Thanks, finally - a bug report!  I just pushed a release with auditing via Spring Boot.  I'll look at this next.  Yep, happens for me, too.

**Comment by binkley** [comment]
Found the cause, have an idea of a solution, need to implement.

I'm calling `AnnotationConfigRegistry::register` in the `@PostConstruct` of `AxonAutoConfiguration`.  When you use `@IntegrationTest` you get the right container implementing this interface; when you use `@WebIntegrationTest` you get a slightly different container which does have a `register` method, but does not implement `AnnotationConfigRegistry`.

I'll replace the `@PostConstruct` method with a bean implementing `ApplicationListener<ContextRefreshedEvent>`, and replace that bean in axon-spring-boot-starter-web module to handle the variance in context implementations.

**Comment by premanandc** [comment]
I forgot to mention that I have a simple solution that works. I'm working
on making it generics aware so that the need for the qualifier annotation
is eliminated. Spring 4 supports generic type declarations as qualifier.

Found the cause, have an idea of a solution, need to implement.

I'm calling AnnotationConfigRegistry::register in the @PostConstruct of
AxonAutoConfiguration. When you use @IntegrationTest you get the right
container implementing this interface; when you use @WebIntegrationTest you
get a slightly different container which does have a register method, but
does not implement AnnotationConfigRegistry.

I'll replace the @PostConstruct method with a bean implementing
ApplicationListener<ContextRefreshedEvent>, and replace that bean in
axon-spring-boot-starter-web module to handle the variance in context
implementations.

**Comment by binkley** [comment]
Fixed for now.  I welcome a better overall solution to autoregistering repositories.

**Comment by GlobalGeneric** [comment]
dsdsd
